# Generated by Django 2.2.7 on 2019-11-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
