# Generated by Django 2.2.7 on 2019-11-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0007_auto_20191106_1842"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redeemable",
            name="currency",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.Currency",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accumulationrule",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accumulation_rules",
                to="programs.Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="redemptionrule",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redemption_rules",
                to="programs.Campaign",
            ),
        ),
    ]
