# Generated by Django 2.2.7 on 2019-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_auto_20191111_0229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
