# Generated by Django 2.2.7 on 2019-11-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0006_redemptionrule_image"),
    ]

    operations = [
        migrations.DeleteModel(name="AccumulationRule",),
    ]
