# Generated by Django 2.2.7 on 2019-11-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_item_image"),
        ("programs", "0009_campaign_points_expire_after"),
        ("rewards", "0007_delete_accumulationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccumulationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveSmallIntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accumulation_rules",
                        to="programs.Campaign",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Category",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Item",
                    ),
                ),
            ],
            options={"unique_together": {("campaign", "category", "item")},},
        ),
    ]
