# Generated by Django 2.2.7 on 2019-11-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0010_auto_20191113_1502"),
        ("rewards", "0009_auto_20191113_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemption",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.Currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="redemption",
            name="value",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
