# Generated by Django 2.2.7 on 2019-11-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0010_auto_20191113_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redemption", name="value", field=models.SmallIntegerField(),
        ),
    ]
