# Generated by Django 2.2.6 on 2019-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programs", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="business", name="address", field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name="business",
            name="phone",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="business", name="url", field=models.URLField(blank=True)
        ),
    ]
