# Generated by Django 2.2.6 on 2019-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("programs", "0002_auto_20191024_1124")]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singular_label", models.CharField(max_length=20)),
                ("plural_label", models.CharField(max_length=20)),
            ],
        )
    ]
