# Generated by Django 2.2.6 on 2019-10-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("programs", "0003_currency")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.Currency",
            ),
        )
    ]
