# Generated by Django 2.2.6 on 2019-10-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("programs", "0004_campaign_currency")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="currency",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.Currency",
            ),
            preserve_default=False,
        )
    ]
