# Generated by Django 2.2.7 on 2019-11-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_auto_20191024_1204"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(blank=True, upload_to="programs/businesses/logos"),
        ),
    ]
