# Generated by Django 2.2.7 on 2019-11-06 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0006_business_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="customers",
            field=models.ManyToManyField(
                related_name="customer_of", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="employees",
            field=models.ManyToManyField(
                related_name="employee_of", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
