# Generated by Django 2.2.7 on 2019-11-10 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0007_auto_20191106_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.Business",
            ),
            preserve_default=False,
        ),
    ]
