# Generated by Django 2.2.7 on 2019-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0008_currency_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="points_expire_after",
            field=models.DurationField(null=True),
        ),
    ]
