# Generated by Django 2.2.7 on 2019-11-13 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0009_campaign_points_expire_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currencies",
                to="programs.Business",
            ),
        ),
    ]
